export const leadersData: Leader[] = [];

export type Successor = {
  nome: string;
  cargo: string | null;
  nivelCarreira: string | null;
  nivelCarreiraPool: string | null;
  prontidao: string | null;
  status: string | null;
  diretoria: string | null;
  ultimoQuadrante: string | null;
  penultimoQuadrante?: string | null;
  enps2025: number | null;
  enps2024?: number | null;
  cr2024?: number | null;
  cr2025?: number | null;
  liderImediato?: string | null;
  tempoNoCargo?: string | null;
  cadastro?: number | null;
  anoIndicacao?: string | null;
};

export type Leader = {
  nome: string;
  cadastro: number | null;
  sexo: string | null;
  situacao: string | null;
  liderDoLider?: string | null;
  cargo: string | null;
  filial: string | null;
  diretoria: string | null;
  ligacaoCE: string | null;
  nivelCarreira: string | null;
  dataAdmissao: string | null;
  dataAdmissaoOriginal?: string | null;
  dataLider: string | null;
  primeiraLideranca: string | null;
  comoSetornouLider?: string | null;
  origemLiderPosicao?: string | null;
  origemLiderPosicaoMacro?: string | null;
  dataInicioCargoAtual?: string | null;
  qtdDiretos: number | null;
  qtdIndiretos: number | null;
  admissoes2025?: number | null;
  penultimoQuadrante?: string | null;
  ultimoQuadrante: string | null;
  conceitoFinal2024: string | null;
  conceitoFocoLiderado2024?: string | null;
  cr2024: number | null;
  cr2025: number | null;
  cr2026?: number | null;
  desejoCarreira2025?: string | null;
  mapeadoSucessor2024?: string | null;
  mapeadoSucessor2025?: string | null;
  enps2024: number | null;
  enps2025: number | null;
  lnps2025: number | null;
  estagioLideranca2024?: string | null;
  estagioLideranca2025: string | null;
  moods2024?: number | null;
  moods2025?: number | null;
  moods2026?: number | null;
  feedback2024?: number | null;
  feedback2025?: number | null;
  turnoverColab2024?: number | null;
  turnoverColab2025?: number | null;
  turnoverEmpresa2024?: number | null;
  turnoverEmpresa2025?: number | null;
  pesqDesligEmpresaEnps2024?: number | null;
  pesqDesligEmpresaEnps2025?: number | null;
  pesqDesligColabEnps2024?: number | null;
  pesqDesligColabEnps2025?: number | null;
  calibradoCE?: string | null;
  calibradoCE2025?: string | null;
  comentarioSituacao?: string | null;
  sucessores: Successor[];
};
